### ISSUE TITLE
cannot convert ‘OSQPWorkspace**’ to ‘const OSQPData*

### ISSUE THREAD

**Issue by dashenyjn123** [robotology/osqp-eigen#102]

**Comment by S-Dafarra** [comment]
Hi @dashenyjn123 could you give us some details? From the title only it is really impossible to understand what is going on

**Comment by GiulioRomualdi** [comment]
Hi @dashenyjn123 noticed that [`OSQPData`](https://osqp.org/docs/interfaces/cc++#_CPPv48OSQPData) and [`OSQPWorkspace`](https://osqp.org/docs/interfaces/cc++#_CPPv413OSQPWorkspace) are two different entities. 
osqp-eigen generates a workspace when the `initSolver` method is called.

https://github.com/robotology/osqp-eigen/blob/c01c310834b749533c63c8c829eab0cde3544d11/src/Solver.cpp#L101-L107
