### ISSUE TITLE
 In the QP problem solving, why the lower triangular matrix using the same data can be solved successfully, but the solution of the upper triangular matrix fails

### ISSUE THREAD

**Issue by Syk-yr** [robotology/osqp-eigen#114]
In the QP problem solving, why the lower triangular matrix using the same data can be solved successfully, but the solution of the upper triangular matrix fails

**Comment by Syk-yr** [comment]
Matrix P=[
2 0 0 0 0 0 0 0 0 0 0 0 
0 2 0 0 0 0 0 0 0 0 0 0 
0 0 2 0 0 0 0 0 0 0 0 0 
0 0 0 2 0 0 0 0 0 0 0 0 
0 0 0 0 1 0 0 0 0 0 0 0 
0 0 0 0 0 1 0 0 0 0 0 0 
0 0 0 0 0 0 1 0 0 0 0 0 
0 0 0 0 0 0 0 1 0 0 0 0 
0 0 0 0 0 0 0 0 26 -50 0 0 
0 0 0 0 0 0 0 0 0 51 -50 0 
0 0 0 0 0 0 0 0 0 0 51 -50 
0 0 0 0 0 0 0 0 0 0 0 26 ]

**Comment by Syk-yr** [comment]
Matrix P=[
2 0 0 0 0 0 0 0 0 0 0 0 
0 2 0 0 0 0 0 0 0 0 0 0 
0 0 2 0 0 0 0 0 0 0 0 0 
0 0 0 2 0 0 0 0 0 0 0 0 
0 0 0 0 1 0 0 0 0 0 0 0 
0 0 0 0 0 1 0 0 0 0 0 0 
0 0 0 0 0 0 1 0 0 0 0 0 
0 0 0 0 0 0 0 1 0 0 0 0 
0 0 0 0 0 0 0 0 26 -50 0 0 
0 0 0 0 0 0 0 0 0 51 -50 0 
0 0 0 0 0 0 0 0 0 0 51 -50 
0 0 0 0 0 0 0 0 0 0 0 26 ]

**Comment by S-Dafarra** [comment]
Hy @Syk-yr, thanks for opening the issue. Just to make sure we are aligned, is the matrix P the cost hessian?

**Comment by S-Dafarra** [comment]
Note that you can obtain the symmetric version of the matrix you have in https://github.com/robotology/osqp-eigen/issues/114#issuecomment-1054208677 by doing (P + P')/2, obtaining
```

P =

     2     0     0     0     0     0     0     0     0     0     0     0
     0     2     0     0     0     0     0     0     0     0     0     0
     0     0     2     0     0     0     0     0     0     0     0     0
     0     0     0     2     0     0     0     0     0     0     0     0
     0     0     0     0     1     0     0     0     0     0     0     0
     0     0     0     0     0     1     0     0     0     0     0     0
     0     0     0     0     0     0     1     0     0     0     0     0
     0     0     0     0     0     0     0     1     0     0     0     0
     0     0     0     0     0     0     0     0    26   -25     0     0
     0     0     0     0     0     0     0     0   -25    51   -25     0
     0     0     0     0     0     0     0     0     0   -25    51   -25
     0     0     0     0     0     0     0     0     0     0   -25    26
```
That is positive definite.

**Comment by Syk-yr** [comment]
Thank you very much for your answer, I see where my mistake is.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Stefano ***@***.***&gt;; 
发送时间: 2022年3月4日(星期五) 凌晨0:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [robotology/osqp-eigen]  In the QP problem solving, why the lower triangular matrix using the same data can be solved successfully, but the solution of the upper triangular matrix fails (Issue #114)






请注意，您可以获得矩阵的对称版本(评论)通过做( P + P ')/ 2 ，获得
 P =      2     0     0     0     0     0     0     0     0     0     0     0      0     2     0     0     0     0     0     0     0     0     0     0      0     0     2     0     0     0     0     0     0     0     0     0      0     0     0     2     0     0     0     0     0     0     0     0      0     0     0     0     1     0     0     0     0     0     0     0      0     0     0     0     0     1     0     0     0     0     0     0      0     0     0     0     0     0     1     0     0     0     0     0      0     0     0     0     0     0     0     1     0     0     0     0      0     0     0     0     0     0     0     0    26   -25     0     0      0     0     0     0     0     0     0     0   -25    51   -25     0      0     0     0     0     0     0     0     0     0   -25    51   -25      0     0     0     0     0     0     0     0     0     0   -25    26 
这是肯定的。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
使用 GitHub Mobile 随时随地发送分流通知IOS 系统或机器人. 
你收到这个，因为你被提到了。留言 ID ***@***.***与&gt;
