### ISSUE TITLE
Migrate Travis to use docker to test on recent linux distributions

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/osqp-eigen#12]
Since the current GNU/Linux distribution supported by Travis is outdated (Ubuntu Trusty), we should update the Travis script to test the library on Ubuntu Xenial or Bionic via docker.

Related to https://github.com/robotology/robotology-superbuild/issues/96

**Comment by traversaro** [comment]
A simple example including only Ubuntu can be found in https://github.com/robotology/sdf-modelica/pull/18 .
