### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jcarpent** [robotology/osqp-eigen#127]
Following #126, it would be nice to get a new release of OSQP-EIGEN mainly for https://github.com/stack-of-tasks/tsid/tree/devel.
@traversaro @GiulioRomualdi do you have a timeline in mind?

Thanks in advance for your help,
Best,

Justin

**Comment by GiulioRomualdi** [comment]
Hi @jcarpent I can create a new release on Monday. Is it fine with you?

**Comment by jcarpent** [comment]
Sounds very perfect from my side. Thanks a lot.
Have a nice weekend!

**Comment by GiulioRomualdi** [comment]
Hi @jcarpent, here you can find the new release: https://github.com/robotology/osqp-eigen/releases/tag/v0.8.0

**Comment by jcarpent** [comment]
Super. Thanks a lot @GiulioRomualdi for this new release.
