### ISSUE TITLE
 there is a problem when building it

### ISSUE THREAD

**Issue by Theyearling** [robotology/osqp-eigen#137]
/home/car/osqp-eigen/include/OsqpEigen/SparseMatrixHelper.hpp:42:37: error: ‘csc’ has not been declared
                                     csc*& osqpSparseMatrix);
                                     ^~~
/home/car/osqp-eigen/include/OsqpEigen/SparseMatrixHelper.hpp:51:56: error: ‘csc’ does not name a type; did you mean ‘cosl’?
         bool osqpSparseMatrixToEigenSparseMatrix(const csc* const & osqpSparseMatrix,
                                                        ^~~
                                                        cosl
/home/car/osqp-eigen/include/OsqpEigen/SparseMatrixHelper.hpp:61:47: error: ‘csc’ does not name a type; did you mean ‘cosl’?
         bool osqpSparseMatrixToTriplets(const csc* const & osqpSparseMatrix,
                                               ^~~
                                               cosl

**Comment by traversaro** [comment]
Hello @jkaob, see https://github.com/robotology/osqp-eigen/issues/135 . 

TL;DR: Now osqp default branch points to the unreleased 1.0.0 version, while osqp-eigen default branch is only compatible with osqp <= 0.6.3 at the moment. If you install osqp 0.6.3 (the latest stable release) everything should work.

**Comment by navil2000** [comment]
Hello, do you know if a new version that is compatible with osqp v1.0.0 is going to be released? Thanks in advance, and great job with the wrapper, very useful :)

**Comment by traversaro** [comment]
> Hello, do you know if a new version that is compatible with osqp v1.0.0 is going to be released? Thanks in advance, and great job with the wrapper, very useful :)

There is an open PR to add osqp 1.0.0 compatibility at https://github.com/robotology/osqp-eigen/pull/131 . Once that is merged, we will do a release.

**Comment by GiulioRomualdi** [comment]
Since https://github.com/robotology/osqp-eigen/pull/131 got merged, master is now compatible with osqp master.

Closing for the time being, in case of issue feel free to open it again 😃
