### ISSUE TITLE
Assert statement in SparseMatrixHelper.tpp

### ISSUE THREAD

**Issue by ghost** [robotology/osqp-eigen#141]
I was able to solve this problem with a little bit of research, but I was wondering if it was possible to include the <cassert> library in SparseMAtrixHelper.tpp. It seems that the way assert statements are handled in g++ 12.2.0 and up are a bit different in that you have to include the assert.h library directly. So instead of:

```
#include <OsqpEigen/Debug.hpp>
.
.
.
    assert(innerOsqpPosition == numberOfNonZeroCoeff); //Will throw an error

```

you must do:

```
#include <OsqpEigen/Debug.hpp>
#include <cassert>
.
.
.
    assert(innerOsqpPosition == numberOfNonZeroCoeff); //Will compile
```

This is something I noticed after compiling osqp-eigen recently and getting this error:

```
 error: there are no arguments to ‘assert’ that depend on a template parameter, so a declaration of ‘assert’ must be available [-fpermissive]
   55 |     assert(innerOsqpPosition == numberOfNonZeroCoeff);

```
and then fixing it after a bit of quick research. I just wanted to bring attention to this so that any future work goes smoothly for anyone else that wants to use this project. Thank you.

**Comment by GiulioRomualdi** [comment]
Closing since https://github.com/robotology/osqp-eigen/pull/130 got merged. Please feel free to open it again in case of issues
