### ISSUE TITLE
auxil.h no such file or directory

### ISSUE THREAD

**Issue by dhananjayrajmane** [robotology/osqp-eigen#159]
In file included from /usr/local/include/OsqpEigen/Solver.hpp:312:0,
                 from /usr/local/include/OsqpEigen/OsqpEigen.h:13,
                 from /root/A1_ctrl_ws/src/A1_Ctrl/src/a1_cpp/src/test/test_rotation.cpp:8:
/usr/local/include/OsqpEigen/Solver.tpp:10:10: fatal error: auxil.h: No such file or directory
 #include <auxil.h>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/test_rotation.dir/src/test/test_rotation.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by traversaro** [comment]
Which version of osqp and osqp-eigen are you using? Thanks!

**Comment by dhananjayrajmane** [comment]
@traversaro  I am using master branches for both . Can you suggest any specific versions for both.
Thanks

**Comment by traversaro** [comment]
If you want to have a configuration that is tested and works fine, I would suggest the last stable release of each:
* https://github.com/osqp/osqp/releases/tag/v0.6.3
* https://github.com/robotology/osqp-eigen/releases/tag/v0.8.1

**Comment by dhananjayrajmane** [comment]
Solved after using above mentioned releases by @traversaro
