### ISSUE TITLE
Trouble installing version 0.7.0 

### ISSUE THREAD

**Issue by jinye1514** [robotology/osqp-eigen#164]
I'm having issues installing the 0.7.0 version of osqp-eigen. I am running ubuntu 20.04 and I ran the following commands
`mkdir build`
`cd build`
`cmake ..`
`make`
after which I get the following errors:
`In file included from /home/andy/osqp-eigen-0.7.0/include/OsqpEigen/Data.hpp:18,
                 from /home/andy/osqp-eigen-0.7.0/src/Data.cpp:12:
/home/andy/osqp-eigen-0.7.0/include/OsqpEigen/SparseMatrixHelper.hpp:42:37: error: ‘csc’ has not been declared
   42 |                                     csc*& osqpSparseMatrix);
      |                                     ^~~
/home/andy/osqp-eigen-0.7.0/include/OsqpEigen/SparseMatrixHelper.hpp:51:56: error: ‘csc’ does not name a type
   51 |         bool osqpSparseMatrixToEigenSparseMatrix(const csc* const & osqpSparseMatrix,
      |                                                        ^~~
/home/andy/osqp-eigen-0.7.0/include/OsqpEigen/SparseMatrixHelper.hpp:61:47: error: ‘csc’ does not name a type
   61 |         bool osqpSparseMatrixToTriplets(const csc* const & osqpSparseMatrix,
      |                                               ^~~
In file included from /home/andy/osqp-eigen-0.7.0/include/OsqpEigen/SparseMatrixHelper.hpp:76,
                 from /home/andy/osqp-eigen-0.7.0/include/OsqpEigen/Data.hpp:18,
                 from /home/andy/osqp-eigen-0.7.0/src/Data.cpp:12:
/home/andy/osqp-eigen-0.7.0/include/OsqpEigen/SparseMatrixHelper.tpp:12:62: error: ‘csc’ has not been declared
   12 |                                                              csc*& osqpSparseMatrix)
      |                                                              ^~~
In file included from /home/andy/osqp-eigen-0.7.0/include/OsqpEigen/SparseMatrixHelper.hpp:76,
                 from /home/andy/osqp-eigen-0.7.0/include/OsqpEigen/Data.hpp:18,
                 from /home/andy/osqp-eigen-0.7.0/src/Data.cpp:12:
/home/andy/osqp-eigen-0.7.0/include/OsqpEigen/SparseMatrixHelper.tpp: In function ‘bool OsqpEigen::SparseMatrixHelper::createOsqpSparseMatrix(const Eigen::SparseCompressedBase<Derived>&, int*&)’:
/home/andy/osqp-eigen-0.7.0/include/OsqpEigen/SparseMatrixHelper.tpp:18:5: error: ‘c_int’ was not declared in this scope; did you mean ‘u_int’?
   18 |     c_int rows = colMajorCopy.rows();
      |     ^~~~~
... ...`

which goes on for 100 more lines. I was able to install the latest commit successfully but not this one, does anyone know what the issue might be?

**Comment by traversaro** [comment]
Which osqp version are you using?

**Comment by jinye1514** [comment]
Same as #165
