### ISSUE TITLE
‘class OsqpEigen::Solver’ has no member named ‘workspace’

### ISSUE THREAD

**Issue by jinye1514** [robotology/osqp-eigen#165]
running Ubuntu 20.04 and version 0.8.1, and I've been running into the following errors:
`error: ‘class OsqpEigen::Solver’ has no member named ‘workspace’
  145 |   num_iter = solver.workspace()->info->iter;`
`error: ‘class OsqpEigen::Solver’ has no member named ‘workspace’
  150 |     cout << "status: " << solver.workspace()->info->status << " status value: " << solver.workspace()->info->status_val << endl;`
`error: ‘class OsqpEigen::Solver’ has no member named ‘workspace’
  150 |     cout << "status: " << solver.workspace()->info->status << " status value: " << solver.workspace()->info->status_val << endl;
`
Anyone know where I should start debugging?

**Comment by traversaro** [comment]
Which version of osqp are you using?

**Comment by jinye1514** [comment]
> Which version of osqp are you using?

osqp version 0.6.3

**Comment by traversaro** [comment]
Which code are you trying to compile? How are you building it? Does the example https://github.com/robotology/osqp-eigen/blob/master/example/src/MPCExample.cpp compile fine for you?

**Comment by jinye1514** [comment]
Oh I think I found the issue, I was accidentally using the beta version of osqp directly cloned from the master branch. Code complied fine once I switch versions!

**Comment by traversaro** [comment]
Ok, feel free to close the issue then.
