### ISSUE TITLE
Could someone kindly explain to me how to use the examples in the “tests”? Thank you.

### ISSUE THREAD

**Issue by moonBuff** [robotology/osqp-eigen#173]
When I try to use the test cases in the tests folder, I get the **error: Unknown CMake command "add_osqpeigen_test"**. I think I might have done something wrong. Could someone please help me figure it out? Thank you!

**Comment by traversaro** [comment]
The files in `tests` are not examples, but rather tests that are supposed to be compiled and run as part of the osqp-eigen CMake build.

Standalone examples that can be built independently from osqp-eigen can be found in https://github.com/robotology/osqp-eigen/tree/master/example .

**Comment by moonBuff** [comment]
I appreciate your prompt response. 
I apologize, as I am a beginner and not very familiar with this project, I misunderstood the purpose of these files. 
Now I have successfully run the example you pointed out to me.
May I ask you again how to run the tests in the tests folder, which you mentioned should be "run as part of the osqp-eigen CMake build"
I'm sorry for bothering you again.

**Comment by moonBuff** [comment]
> The files in `tests` are not examples, but rather tests that are supposed to be compiled and run as part of the osqp-eigen CMake build.
> 
> Standalone examples that can be built independently from osqp-eigen can be found in https://github.com/robotology/osqp-eigen/tree/master/example .

I appreciate your prompt response.
I apologize, as I am a beginner and not very familiar with this project, I misunderstood the purpose of these files.
Now I have successfully run the example you pointed out to me.
May I ask you again how to run the tests in the tests folder, which you mentioned should be "run as part of the osqp-eigen CMake build"
I'm sorry for bothering you again.

**Comment by traversaro** [comment]
In general, you can compile the project and the tests with this commands on Linux and macOS:

~~~
git clone https://github.com/robotology/osqp-eigen
cd osqp-eigen
cmake -Bbuild -S. -DBUILD_TESTING:BOOL=ON
cd build
make
make test
~~~

However, you need to make sure that you have all the required depencies (like osqp, eigen and catch2). So to provide an helpful answer, we need to know:
* On which operating system are you?
* Which package manager are you using to install C++ dependencies?

**Comment by moonBuff** [comment]
> In general, you can compile the project and the tests with this commands on Linux and macOS:
> 
> ```
> git clone https://github.com/robotology/osqp-eigen
> cd osqp-eigen
> cmake -Bbuild -S. -DBUILD_TESTING:BOOL=ON
> cd build
> make
> make test
> ```
> 
> However, you need to make sure that you have all the required depencies (like osqp, eigen and catch2). So to provide an helpful answer, we need to know:
> 
> * On which operating system are you?
> * Which package manager are you using to install C++ dependencies?

Your assistance has been so prompt that I can hardly express my gratitude. I'm very sorry that I may not be able to respond as quickly as you reply to me. We might be in different time zones, so I may need to wait until the next day to respond to your help.

What follows might raise your blood pressure, as I am truly a beginner without much understanding. However, by chance, I now find myself needing to work with OSQP-related content.

I'm working in a **Windows** environment and trying to run this project. My package manager is **vcpkg**, but it seems that the vcpkg library only contains Catch2 and Eigen3, without support for osqp and osqp-eigen.

As a result, I downloaded osqp and osqp-eigen directly using git clone. To run the MPCExample in osqp-eigen, **I configured it in Visual Studio 2022 by going to Project > Properties > VC++ Directories > Library Directories and Include Directories, where I included the paths for the osqp and osqp-eigen repositories I cloned. I then added the .lib files to Linker > Input > Additional Dependencies.**

Now, I want to run the tests in the tests folder, but I'm running into issues where **vcpkg can't find the manually downloaded osqp and osqp-eigen libraries,** even after adding set and find_package statements to the CMakeLists.txt in osqp-eigen.

Since I'm quite new to this, I might be getting things tangled up due to my lack of experience.

I want to thank you once again for your selfless assistance.

**Comment by traversaro** [comment]
> Your assistance has been so prompt that I can hardly express my gratitude. I'm very sorry that I may not be able to respond as quickly as you reply to me. We might be in different time zones,.It’s already quite late here, and I don't want to disturb my roommate as our dorm room is quite small. So I apologize that I might not be able to respond to your help until tomorrow.
>
> What follows might raise your blood pressure, as I am truly a beginner without much understanding. However, by chance, I now find myself needing to work with OSQP-related content.

No need to worry, really.

If you are working with vcpkg, the following commands should be sufficient to run the tests with vcpkg provided dependencies. First of all, open your "x64 Native Tools command prompt for VS2022" (or VS2019 if using an earlier version). 

First of all, create a clean directory called osqpeigenws in your home:
~~~
cd %USERPROFILE%
mkdir osqpeigenws
~~~

In there, clone vcpkg and install there catch2 and eigen:
~~~
cd %USERPROFILE%\osqpeigenws
git clone https://github.com/microsoft/vcpkg
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg.exe install catch2 eigen3
~~~

If the installation was successful, go back in `osqpeigenws` to download and compile osqp and osqp-eigen. We are going to install the libraries in `%HOMEPATH%\osqpeigenws\install`, and we will add this directory to `CMAKE_PREFIX_PATH` to ensure that it is found. We are also going to use the branch https://github.com/robotology/osqp-eigen/pull/171 for osqp-eigen, to have support for a modern catch as the one installed by default by vcpkg:

~~~
cd %USERPROFILE%\osqpeigenws
git clone --recursive -b release-0.6.3 https://github.com/osqp/osqp
git clone -b cleanupci https://github.com/robotology/osqp-eigen
cd osqp
cmake -Bbuild -S. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%USERPROFILE%\osqpeigenws\install
cmake --build ./build --config Release
cmake --install ./build --config Release
cd %USERPROFILE%\osqpeigenws
cd osqp-eigen
cmake -Bbuild -S. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH==%USERPROFILE%\osqpeigenws\install -DCMAKE_INSTALL_PREFIX=%USERPROFILE%\osqpeigenws -DBUILD_TESTING:BOOL=ON -DCMAKE_TOOLCHAIN_FILE=%USERPROFILE%\osqpeigenws\vcpkg\scripts\buildsystems\vcpkg.cmake
cmake --build ./build --config Release
cmake --install ./build --config Release
~~~

At this point, you can run the tests with the `ctest` command:

~~~
cd %USERPROFILE%\osqpeigenws\osqp-eigen\build
ctest -C Release 
~~~

If everything works correctly, you should see the tests running with output:

~~~
C:\Users\straversaro\osqpeigenws\osqp-eigen\build>ctest -C Release
Test project C:/Users/straversaro/osqpeigenws/osqp-eigen/build
    Start 1: SparseMatrixUnitTests
1/5 Test #1: SparseMatrixUnitTests ............   Passed    0.12 sec
    Start 2: QPUnitTests
2/5 Test #2: QPUnitTests ......................   Passed    0.07 sec
    Start 3: UpdateMatricesUnitTests
3/5 Test #3: UpdateMatricesUnitTests ..........   Passed    0.06 sec
    Start 4: MPCUnitTests
4/5 Test #4: MPCUnitTests .....................   Passed    0.10 sec
    Start 5: MPCUpdateMatricesUnitTests
5/5 Test #5: MPCUpdateMatricesUnitTests .......   Passed    0.09 sec
~~~

On a related note, apparently somebody is working on packaging osqp and osqp-eigen on vcpkg, see: https://github.com/microsoft/vcpkg/pull/39629 and https://github.com/microsoft/vcpkg/pull/41676. However, this is not ready at the moment.
