### ISSUE TITLE
A beginner would like to ask how to set the lower and upper bounds of variables

### ISSUE THREAD

**Issue by moonBuff** [robotology/osqp-eigen#177]
I have a question: in addition to the constraints, the variables themselves also have their own lower and upper bounds. 
I used setLowerBound and setUpperBound to pass the bounds of the constraints to the solver, but now I don't know how to pass the variables' own bounds. 
The specific content of the problem is shown in the attached file. My confusion is how to pass the section under 'bounds' in the txt file to the solver.
I'd appreciate any guidance. Thank you very much!
[QPlib10034.txt](https://github.com/user-attachments/files/17744201/QPlib10034.txt)

**Comment by traversaro** [comment]
Variable bounds can be passed as generic linear bounds by using an identity matrix as a constraint matrix.

**Comment by traversaro** [comment]
Like if you have variable boundaries $l_v < x < u_v$ and generic linear boundaries $l_g < C_g x < u_g$, you can define them all as generic with:

$$
l' =
\begin{bmatrix}
l_v \\
l_g \\
\end{bmatrix}
$$

$$
u' =
\begin{bmatrix}
u_v \\
u_g \\
\end{bmatrix}
$$

$$
C'
=
\begin{bmatrix}
I \\
C_g \\
\end{bmatrix}

$$

where $I$ is the identity matrix.

**Comment by moonBuff** [comment]
> Variable bounds can be passed as generic linear bounds by using an identity matrix as a constraint matrix.

Thank you very much for your help. I think I now have a general idea of how to handle this type of issue. Thank you again!

**Comment by traversaro** [comment]
If you solved your problem, feel free to close the issue.
