### ISSUE TITLE
[OsqpEigen::Solver::initSolver] Unable to setup the workspace. On ros2 project

### ISSUE THREAD

**Issue by liops-bumgyu** [robotology/osqp-eigen#180]
I'm trying to make a MPC using osqp-eigen. My osqp version is the latest 1.0.0.beta0.

Whenever I try to initialize the solver, I get "[OsqpEigen::Solver::initSolver] Unable to setup the workspace." error. 

I'm pretty sure that problem is not related to dimensions because I've printed out all the dimensions of matrixes and vectors to debug.

Can this problem related with ros2?

The following code is problem update function for MPC.

  int Controller::update_problem()
  {
    
    
    quadratic_part = make_quadratic_part(state_trajectory);
    RCLCPP_DEBUG(this->get_logger(), "quadratic_part_made (%ld, %ld)", quadratic_part.rows(), quadratic_part.cols());

    update_benchmark_trajectory(state_trajectory, new_path, current_state);
    RCLCPP_DEBUG(this->get_logger(), "benchmark_updated");

    linear_part = make_linear_part(state_trajectory);
    RCLCPP_DEBUG(this->get_logger(), "linear_part_made (%ld)", linear_part.rows());

    constraint_part = make_constraint_part(state_trajectory);
    RCLCPP_DEBUG(this->get_logger(), "constraint_part_made (%ld, %ld)", constraint_part.rows(), constraint_part.cols());
    lower_bound = make_lower_bound(state_trajectory);
    RCLCPP_DEBUG(this->get_logger(), "lower_bound_made (%ld)", lower_bound.rows());
    upper_bound = make_upper_bound(state_trajectory);
    RCLCPP_DEBUG(this->get_logger(), "upper_bound_made (%ld)", upper_bound.rows());
    
    /*std::stringstream ss;
    ss << quadratic_part;

    RCLCPP_DEBUG(this->get_logger(), "quadratic_part : \n%s", ss.str().c_str());*/

    if(!solver.isInitialized()){
      RCLCPP_DEBUG(this->get_logger(), "initalizing_solver.");
      solver.data()->setHessianMatrix(quadratic_part);
      solver.data()->setGradient(linear_part);
      solver.data()->setLinearConstraintsMatrix(constraint_part);
      solver.data()->setLowerBound(lower_bound);
      solver.data()->setUpperBound(upper_bound);
      if(!solver.initSolver()){
        return 6;
      }
      return 0;
    }
    
    if (!solver.updateHessianMatrix(quadratic_part)){
      return 1;
    }
    if (!solver.updateGradient(linear_part)){
      return 2;
    }
    if (!solver.updateLinearConstraintsMatrix(constraint_part)){
      return 3;
    }
    if (!solver.updateLowerBound(lower_bound)){
      return 4;
    }
    if (!solver.updateUpperBound(upper_bound)){
      return 5;
    }
    RCLCPP_DEBUG(this->get_logger(), "update_problem_out");
    return 0;
  }

**Comment by traversaro** [comment]
Unless you can provide a [Minimal and Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) of your problem it may be difficult for users to help you.

**Comment by liops-bumgyu** [comment]
The issue was with the bound settings. I accidentally assigned some of the lower_bound arguments to be greater than the upper_bound. After correcting this part, the error messages no longer appeared, and the calculations proceeded normally.

**Comment by traversaro** [comment]
> The issue was with the bound settings. I accidentally assigned some of the lower_bound arguments to be greater than the upper_bound. After correcting this part, the error messages no longer appeared, and the calculations proceeded normally.

Thanks for the update!
