### ISSUE TITLE
API of getting dual solution

### ISSUE THREAD

**Issue by chibi314** [robotology/osqp-eigen#21]
Hi.

I'd like to get the dual solution (y), but couldn't find the API.
In [Solver.hpp](https://github.com/robotology/osqp-eigen/blob/master/include/OsqpEigen/Solver.hpp), there's `getDualSolution` API which gives `m_workspace->solution->x`.
I also want to get `m_workspace->solution->y`.

Thanks!

**Comment by chibi314** [comment]
Can I send a PR about this?

**Comment by GiulioRomualdi** [comment]
Hi @chibi314! Thank you very much! You can open the PR
