### ISSUE TITLE
Deleted move constructor of Solver

### ISSUE THREAD

**Issue by chibi314** [robotology/osqp-eigen#37]
https://github.com/robotology/osqp-eigen/blob/master/include/OsqpEigen/Solver.hpp
The move constructor of class Solver is implicitly deleted.
Therefore the instance of Solver is unable to move.
Is there any reason of forbidding move operation?
If no, can I add default move constructor?

**Comment by GiulioRomualdi** [comment]
Hi @chibi314 sorry for the late response, I completely forgot the issue. There is no reason. I will add it along with the `copy constructor`, `copy assignment operator` and `move assignment operator` in the next future.

**Comment by GiulioRomualdi** [comment]
Hi @chibi314 #47 should solve your issue
