### ISSUE TITLE
How to set run time limit?

### ISSUE THREAD

**Issue by LiJiangnanBit** [robotology/osqp-eigen#38]
Is there any setting for time limit, like the original osqp setting?
![image](https://user-images.githubusercontent.com/23288471/69492610-dd35ae00-0edf-11ea-855b-8aaa11fef928.png)
usually it takes longer if the solver fails. I want to set a limit for run time.
Thanks!

**Comment by S-Dafarra** [comment]
Hello @LiJiangnanBit, sorry for the late answer.

Actually you can already through ``getSettings()``, i.e.
```c++
OsqpEigen::Solver solver();
.
.
.
solver.settings()->getSettings()->time_limit = (c_float)timeLimit;
```

I did not test this code though, there may be some imprecision.
In the meanwhile, I also opened a PR to add a ``setTimeLimit`` method to the ``Settings`` class: https://github.com/robotology/osqp-eigen/pull/52

**Comment by LiJiangnanBit** [comment]
Thanks 😊
