### ISSUE TITLE
My commit is deleted

### ISSUE THREAD

**Issue by chibi314** [robotology/osqp-eigen#45]
I send a PR #25 and it was merged into `devel`, but now I couldn't find it in `devel` and `master`.

**Comment by GiulioRomualdi** [comment]
Dear @chibi314, I am investigating. I'll answer soon

**Comment by GiulioRomualdi** [comment]
Seems that a cleanup has removed your commits. I am kindly asking you to open a new PR on `devel` with the code updating the [project version](https://github.com/robotology/osqp-eigen/blob/master/CMakeLists.txt#L30) to `0.5.103`.

**Comment by S-Dafarra** [comment]
To be honest, I do not know how this could have happened. It is possible that some rebase caused that commit to be deleted. I apologize for that.

I have branched and rebased the branch https://github.com/chibi314/osqp-eigen/tree/add_get_dual_solution and opened a PR: https://github.com/robotology/osqp-eigen/pull/50

**Comment by S-Dafarra** [comment]
The PR #50 has been merged. I think we can close this issue.
