### ISSUE TITLE
Drop Google test in favor of Catch2 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/osqp-eigen#58]
`Google Test` from the next releases will start to depend on `abseil`, see [here](https://github.com/google/googletest/blob/master/README.md#coming-soon). `Abseil` is a quite big  C++ library that is not packaged in Ubuntu or Homebrew (see https://repology.org/project/abseil-cpp/versions), and will make `Google Test` a non-trivial dependency to obtain. On light of this I would propose moving from `Google Test` to `Catch2`.

@traversaro and @S-Dafarra

**Comment by S-Dafarra** [comment]
Agree!

**Comment by GiulioRomualdi** [comment]
Closed with #59
