### ISSUE TITLE
 osqp.h: No such file or directory  #include <osqp.h>

### ISSUE THREAD

**Issue by mzahana** [robotology/osqp-eigen#67]
Hi.

I installed `osqp` from source as described [here](https://osqp.org/docs/get_started/sources.html). Then, I installed `osqp-eigen`. I installed both system wide.

I am using `catkin build` to build my applications. In my CMakeLists.txt, I set the following,
```
find_package(OsqpEigen)
find_package(osqp REQUIRED)
```

I use the following include in my header file
```cpp
#include "OsqpEigen/OsqpEigen.h"
```

When I try to compile, I get
```sh
 osqp.h: No such file or directory  #include <osqp.h>
```

Any advice on how to solve this issue?

Thanks.

**Comment by S-Dafarra** [comment]
Hi @mzahana, thanks for using ``OsqpEigen``. My best guess at the moment would be to try linking ``osqp::osqp`` in your application using [``target_link_libraries``](https://cmake.org/cmake/help/v3.12/command/target_link_libraries.html) in your ``CMakeLists``. If you have any link to your application, we may try to provide more insights.

**Comment by mzahana** [comment]
@S-Dafarra thank you for your reply. I did that and still getting the error

This is what I use in the `CMakeLists` 
```
find_package(OsqpEigen)
find_package(osqp REQUIRED)
.
.
.

add_executable(mpc_tracker_node
  src/mpc_tracker_node.cpp
)
add_dependencies(mpc_tracker_node mpc_tracker ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
target_link_libraries(mpc_tracker_node mpc_tracker ${catkin_LIBRARIES} ${nlopt_LIBRARIES} osqp::osqp)
```

The error looks like:
```sh
from /home/arrow/catkin_ws/src/mavros_apriltag_tracking/src/mpc_tracker.cpp:32:
/usr/local/include/OsqpEigen/Constants.hpp:12:10: fatal error: osqp.h: No such file or directory
 #include <osqp.h>

```

**Comment by mzahana** [comment]
So, I got it compiled by having `OsqpEigen` in `find_package()` in the following way
```
find_package(catkin REQUIRED COMPONENTS
  some_packages
.
.
.
  OsqpEigen
)
```
It compiled without having to link `osqp::osqp`

Up to now, I just included the `#include <OsqpEigen/OsqpEigen.h>`. Didn't do anything else as I wanted to make sure the include is OK.

**Comment by S-Dafarra** [comment]
> So, I got it compiled by having `OsqpEigen` in `find_package()` in the following way
> 
> ```
> find_package(catkin REQUIRED COMPONENTS
>   some_packages
> .
> .
> .
>   OsqpEigen
> )
> ```
> 
> It compiled without having to link `osqp::osqp`
> 
> Up to now, I just included the `#include <OsqpEigen/OsqpEigen.h>`. Didn't do anything else as I wanted to make sure the include is OK.

Sounds good! Then probably ``OsqpEigen::OsqpEigen`` was missing as a target to link.

**Comment by S-Dafarra** [comment]
@mzahana if this is no more an issue, feel free to close it.
