### ISSUE TITLE
when i build my project , it shows that it cant find osqg.h

### ISSUE THREAD

**Issue by Richard-LXA** [robotology/osqp-eigen#71]
In file included from /usr/local/include/OsqpEigen/OsqpEigen.h:10:0,
                 from /home/ruoyo/car/nav_ws/src/trajectory_planning/src/hard_constrained/trajectory_corridor-based.cpp:6:
/usr/local/include/OsqpEigen/Constants.hpp:12:10: fatal error: osqp.h: No such file or directory
 #include <osqp.h>
          ^~~~~~~~
compilation terminated.
CMakeFiles/CTG.dir/build.make:62: recipe for target 'CMakeFiles/CTG.dir/src/hard_constrained/trajectory_corridor-based.cpp.o' failed
make[3]: *** [CMakeFiles/CTG.dir/src/hard_constrained/trajectory_corridor-based.cpp.o] Error 1
CMakeFiles/Makefile2:2278: recipe for target 'CMakeFiles/CTG.dir/all' failed
make[2]: *** [CMakeFiles/CTG.dir/all] Error 2
CMakeFiles/Makefile2:233: recipe for target 'CMakeFiles/main.dir/rule' failed
make[1]: *** [CMakeFiles/main.dir/rule] Error 2
Makefile:175: recipe for target 'main' failed
make: *** [main] Error 2

**Comment by mzahana** [comment]
@Richard-LXA Did you find a solution to this issue?

**Comment by traversaro** [comment]
Hi @mzahana, if you have any problem feel free to open a new issue, thanks!
