### ISSUE TITLE
Add possibility (e.g. cmake flag) to disable or redirect error output

### ISSUE THREAD

**Issue by kalj** [robotology/osqp-eigen#74]
Currently, there are hard coded unconditional error messages using `std::cerr` which cannot be disabled. It would be great if it would be possible to disable them, or perhaps define your own log callback which is invoked to print the messages. This would allow an application using `osqp-eigen` to incorporate these error messages in whatever logging framework it prefers.

**Comment by S-Dafarra** [comment]
Hi @kalj, thanks a lot for the suggestion. It makes definitely sense. It is something we did not consider while developing it. Also, feel free to open a PR for it. 

cc @GiulioRomualdi
