### ISSUE TITLE
Forward merge master to devel

### ISSUE THREAD

**Issue by traversaro** [robotology/osqp-eigen#85]
@GiulioRomualdi can you forward merge master to devel? The Unstable branches of the superbuild seems to be broken otherwise: https://github.com/robotology/robotology-superbuild/runs/2091673792?check_suite_focus=true .

**Comment by traversaro** [comment]
Apparently devel is not going to be updated anymore, see https://github.com/robotology/robotology-superbuild/pull/655 .

**Comment by GiulioRomualdi** [comment]
Since  robotology/robotology-superbuild#655 has been merged, I deleted the devel branch
